name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'sdk/**/*.xml'
      - clonk.xsl
      - '**/*.scss'
      - '**/*.ts'
      - '**/*.py'
      - '**/*.html'
      - 'Makefile'
      - 'images/**'
      - '*.po'
      - '.github/worflows/build.yml'

  pull_request:
    types: [ ready_for_review ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Ubuntu 18.04: Setup chroot"
        run: |
          curl -L https://github.com/legacyclonk/ubuntu-1804-x86-chroot/releases/download/2022-05-19/chroot.tar.xz | sudo tar -xJ
          curl -L https://raw.githubusercontent.com/legacyclonk/ubuntu-1804-x86-chroot/master/setup_chroot.sh | sudo bash -e -
          sudo mkdir -p chroot/$PWD
          sudo mount --bind . chroot/$PWD
          echo "CHROOT=$PWD/.github/workflows/Linux-x86-chroot.sh" >> $GITHUB_ENV

      - name: Setup saxonb-xslt, python, gettext, Mako (Python templating engine), typescript compiler, sass (scss compiler)
        run: |
          $CHROOT sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends libsaxonb-java python-libxml2 gettext openjdk-11-jre-headless python3-mako curl -y
          $CHROOT cd /usr/local \&\& \(curl -L https://unofficial-builds.nodejs.org/download/release/v21.7.3/node-v21.7.3-linux-x86.tar.xz \| tar --strip-components=1 -xJ\)
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
          $CHROOT cd ./developer \&\& npm ci

      - name: Build docs
        run: |
          $CHROOT make all -j$(nproc)

      - name: "Collect artifacts"
        run: |
          sudo chown -R $UID online sdk-en sdk doku.pot lcdocs_summary.json
          [ -f en.mo ] && sudo chown $UID en.mo
          mkdir output
          mv online output
          mv sdk-en output
          mv sdk output
          mv doku.pot output
          [ -f en.mo ] && mv en.mo output
          mv lcdocs_summary.json output
          cd output

      - name: "Publish full output"
        uses: actions/upload-artifact@v6
        with:
          name: generated-full
          path: output/*

      - name: "Publish html help only"
        uses: actions/upload-artifact@v6
        with:
          name: html-help
          path: output/online/*
