name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'sdk/**/*.xml'
      - clonk.xsl
      - '**/*.scss'
      - '**/*.ts'
      - '**/*.py'
      - '**/*.html'
      - 'Makefile'
      - 'images/**'
      - '*.po'
      - '.github/worflows/build.yml'

  pull_request:
    types: [ ready_for_review ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Ubuntu 18.04: Setup chroot"
        run: |
          curl -L https://github.com/legacyclonk/ubuntu-1804-x86-chroot/releases/download/2022-05-19/chroot.tar.xz | sudo tar -xJ
          curl -L https://raw.githubusercontent.com/legacyclonk/ubuntu-1804-x86-chroot/master/setup_chroot.sh | sudo bash -e -
          sudo mkdir -p chroot/$PWD
          sudo mount --bind . chroot/$PWD
          echo "CHROOT=$PWD/.github/workflows/Linux-x86-chroot.sh" >> $GITHUB_ENV

      - name: Setup saxonb-xslt, python, gettext, Mako (Python templating engine), typescript compiler, sass (scss compiler)
        run: |
          $CHROOT sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends libsaxonb-java python-libxml2 gettext nodejs npm openjdk-11-jre-headless -y
          $CHROOT pip3 install -r developer/requirements.txt
          (cd ./developer && $CHROOT npm ci)

      - name: Build docs
        run: |
          $CHROOT make all -j$(nproc)

      - name: "Collect artifacts"
        run: |
          mkdir output
          mv online output
          mv sdk-en output
          mv sdk output
          mv doku.pot output
          [ -f en.mo ] && mv en.mo output
          mv lcdocs_summary.json output
          cd output
          zip -q -0 -r ../generated-docs.zip *

      - name: "Publish zipped Main Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: generated-docs-nested-zip
          path: generated-docs.zip
